service: alexa-losung-skill

provider:
  name: aws
  runtime: nodejs6.10
  region: eu-west-1

package:
  individually: true
  exclude:
    - '**'

functions:
  skill:
    handler: build/skill.handler
    package:
      include:
        - build/skill*
    events:
      - alexaSkill
  flash-briefing:
    handler: build/flashBriefing.handler
    package:
      include:
        - build/flashBriefing*
    events:
      - http:
          path: today
          method: get
          integration: LAMBDA
