service: alexa-losung-skill

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1
  memorySize: 128

package:
  individually: true
  excludeDevDependencies: false
  exclude:
    - '**'

functions:
  skill:
    handler: dist/index.handler
    package:
      include:
        - dist/index*
        - dist/data/*
    events:
      - alexaSkill: amzn1.ask.skill.c39a3d20-a390-4a89-915b-5040dda5e467
  flash-briefing:
    handler: dist/flash-briefing.handler
    package:
      include:
        - dist/flash-briefing*
        - dist/data/*
    events:
      - http:
          path: today
          method: get
          integration: LAMBDA
